### ISSUE TITLE
Changing font at the wrong time.

### ISSUE THREAD

**Issue by cjwelborn** [tsenart/sight#67] opened 2015-07-20 22:22 UTC
I go to download a python source file, Chrome's dialog pops up so I can save the file (because of my static server's mime-type association with `.py` files). If I cancel the dialog, Sight will change the body of whatever page I am viewing to it's chosen monospace font and size.

The site you see in these images is my personal site. It has some links to download source files, and this is where I first saw the bug.

Before downloading the source file:
![image](https://cloud.githubusercontent.com/assets/3335984/8788705/d1a6ec56-2f01-11e5-8435-5278e15e7c82.png)

Click to download a source file, dialog pops up:
![image](https://cloud.githubusercontent.com/assets/3335984/8788720/f08004be-2f01-11e5-8fa3-3656580761c1.png)

Now the body font has changed:
![image](https://cloud.githubusercontent.com/assets/3335984/8788732/052afcac-2f02-11e5-99e5-1c6663cb95ad.png)

Disabling Sight corrects the issue, so I'm positive it's Sight doing it. The `DejaVuSansMono` and `font-size:small` are my Sight settings. Sight seems to think that I have downloaded the file and I'm viewing it. When the url uses the `file://` protocol Chrome will open the file in a new tab and Sight will do the correct thing.

**Comment by cjwelborn** [comment] 2015-07-20 22:30
By the way, here is my browser info:

Name | Version
| --- | --- | 
Google Chrome | `43.0.2357.134 (Official Build) (64-bit)`
Revision            | `8f3081cb09276898e725262e5ca6ec7746757188-refs/branch-heads/2357@{#499}` 
OS	                  | `Linux `

**Comment by tsenart** [comment] 2015-07-21 15:39
Duplicate of #65

**Closed by tsenart** 2015-07-21 15:39 UTC
